using System;
using System.Runtime.InteropServices;
using Windows.Win32.Interop;

namespace Windows.Win32.Security
{
    [Flags]
    public enum CREDUI_FLAGS
    {
        CREDUI_FLAGS_ALWAYS_SHOW_UI = 0x00080,
        CREDUI_FLAGS_COMPLETE_USERNAME = 0x00800,
        CREDUI_FLAGS_DO_NOT_PERSIST = 0x00002,
        CREDUI_FLAGS_EXCLUDE_CERTIFICATES = 0x00008,
        CREDUI_FLAGS_EXPECT_CONFIRMATION = 0x20000,
        CREDUI_FLAGS_GENERIC_CREDENTIALS = 0x40000,
        CREDUI_FLAGS_INCORRECT_PASSWORD = 0x00001,
        CREDUI_FLAGS_KEEP_USERNAME = 0x100000,
        CREDUI_FLAGS_PASSWORD_ONLY_OK = 0x00200,
        CREDUI_FLAGS_PERSIST = 0x01000,
        CREDUI_FLAGS_REQUEST_ADMINISTRATOR = 0x00004,
        CREDUI_FLAGS_REQUIRE_CERTIFICATE = 0x00010,
        CREDUI_FLAGS_REQUIRE_SMARTCARD = 0x00100,
        CREDUI_FLAGS_SERVER_CREDENTIAL = 0x04000,
        CREDUI_FLAGS_SHOW_SAVE_CHECK_BOX = 0x00040,
        CREDUI_FLAGS_USERNAME_TARGET_CREDENTIALS = 0x80000,
        CREDUI_FLAGS_VALIDATE_USERNAME = 0x00400
    }

    [Flags]
    public enum CREDUIWIN
    {
        CREDUIWIN_GENERIC = 0x00000001,
        CREDUIWIN_CHECKBOX = 0x00000002,
        CREDUIWIN_AUTHPACKAGE_ONLY = 0x00000010,
        CREDUIWIN_IN_CRED_ONLY = 0x00000020,
        CREDUIWIN_ENUMERATE_ADMINS = 0x00000100,
        CREDUIWIN_ENUMERATE_CURRENT_USER = 0x00000200,
        CREDUIWIN_SECURE_PROMPT = 0x00001000,
        CREDUIWIN_PREPROMPTING = 0X00002000,
        CREDUIWIN_PACK_32_WOW = 0x10000000
    }

    public enum CERT_QUERY_OBJECT_TYPE : uint
    {
        CERT_QUERY_OBJECT_FILE = 0x00000001,
        CERT_QUERY_OBJECT_BLOB = 0x00000002
    }

    public enum CERT_QUERY_CONTENT_TYPE : uint
    {
        CERT_QUERY_CONTENT_CERT = 1,
        CERT_QUERY_CONTENT_CTL = 2,
        CERT_QUERY_CONTENT_CRL = 3,
        CERT_QUERY_CONTENT_SERIALIZED_STORE = 4,
        CERT_QUERY_CONTENT_SERIALIZED_CERT = 5,
        CERT_QUERY_CONTENT_SERIALIZED_CTL = 6,
        CERT_QUERY_CONTENT_SERIALIZED_CRL = 7,
        CERT_QUERY_CONTENT_PKCS7_SIGNED = 8,
        CERT_QUERY_CONTENT_PKCS7_UNSIGNED = 9,
        CERT_QUERY_CONTENT_PKCS7_SIGNED_EMBED = 10,
        CERT_QUERY_CONTENT_PKCS10 = 11,
        CERT_QUERY_CONTENT_PFX = 12,
        CERT_QUERY_CONTENT_CERT_PAIR = 13,
        CERT_QUERY_CONTENT_PFX_AND_LOAD = 14
    }

    [Flags]
    public enum CERT_QUERY_CONTENT_FLAGS : uint
    {
        CERT_QUERY_CONTENT_FLAG_CERT = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_CERT,
        CERT_QUERY_CONTENT_FLAG_CTL = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_CTL,
        CERT_QUERY_CONTENT_FLAG_CRL = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_CRL,
        CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_SERIALIZED_STORE,
        CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_SERIALIZED_CERT,
        CERT_QUERY_CONTENT_FLAG_SERIALIZED_CTL = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_SERIALIZED_CTL,
        CERT_QUERY_CONTENT_FLAG_SERIALIZED_CRL = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_SERIALIZED_CRL,
        CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PKCS7_SIGNED,
        CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PKCS7_UNSIGNED,
        CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PKCS7_SIGNED_EMBED,
        CERT_QUERY_CONTENT_FLAG_PKCS10 = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PKCS10,
        CERT_QUERY_CONTENT_FLAG_PFX = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PFX,
        CERT_QUERY_CONTENT_FLAG_CERT_PAIR = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_CERT_PAIR,
        CERT_QUERY_CONTENT_FLAG_PFX_AND_LOAD = 1 << (int)CERT_QUERY_CONTENT_TYPE.CERT_QUERY_CONTENT_PFX_AND_LOAD,
        CERT_QUERY_CONTENT_FLAG_ALL = CERT_QUERY_CONTENT_FLAG_CERT | CERT_QUERY_CONTENT_FLAG_CTL | CERT_QUERY_CONTENT_FLAG_CRL | CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE | CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT | CERT_QUERY_CONTENT_FLAG_SERIALIZED_CTL | CERT_QUERY_CONTENT_FLAG_SERIALIZED_CRL | CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED | CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED | CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED |  CERT_QUERY_CONTENT_FLAG_PKCS10 | CERT_QUERY_CONTENT_FLAG_PFX | CERT_QUERY_CONTENT_FLAG_CERT_PAIR,
        CERT_QUERY_CONTENT_FLAG_ALL_ISSUER_CERT = CERT_QUERY_CONTENT_FLAG_CERT | CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE | CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT | CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED | CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED
    }

    public enum CERT_QUERY_FORMAT : uint
    {
        CERT_QUERY_FORMAT_BINARY = 1,
        CERT_QUERY_FORMAT_BASE64_ENCODED = 2,
        CERT_QUERY_FORMAT_ASN_ASCII_HEX_ENCODED = 3
    }

    [Flags]
    public enum CERT_QUERY_FORMAT_FLAGS : uint
    {
        CERT_QUERY_FORMAT_FLAG_BINARY = 1 << (int)CERT_QUERY_FORMAT.CERT_QUERY_FORMAT_BINARY,
        CERT_QUERY_FORMAT_FLAG_BASE64_ENCODED = 1 << (int)CERT_QUERY_FORMAT.CERT_QUERY_FORMAT_BASE64_ENCODED,
        CERT_QUERY_FORMAT_FLAG_ASN_ASCII_HEX_ENCODED = 1 << (int)CERT_QUERY_FORMAT.CERT_QUERY_FORMAT_ASN_ASCII_HEX_ENCODED,
        CERT_QUERY_FORMAT_FLAG_ALL = CERT_QUERY_FORMAT_FLAG_BINARY | CERT_QUERY_FORMAT_FLAG_BASE64_ENCODED | CERT_QUERY_FORMAT_FLAG_ASN_ASCII_HEX_ENCODED
    }
}
